#!/bin/zsh
#
alias casinodev='ssh casino@game.dev.a8casino.com'
alias tget="tsocks wget"
alias tumx='tmux'
alias ta='tmux attach'
alias tt='tmux new -A -s $USER'
alias httpserver="python -m SimpleHTTPServer 8888"
alias "brewi"="brew install --build-from-source"
alias "tbrewi"="tsocks brew install --build-from-source"
alias src='cd $GOPATH/src/najaplus.com/'
# tmux_porcess_cnt=`pgrep tmux |wc -l`

# if [ $tmux_porcess_cnt -eq 0  ] ; then
#     tmux new -A -s $HOST
# else
if [[ "$TERM" != "dumb" ]]; then
    echo "tt for tmux new -A -s $USER"
    echo "ta for tmux attach"
fi
# fi

# alias ubuntu="ssh ubuntu@42.62.77.86"
alias deployer="ssh deployer@src.najaplus.com"
# alias copyright="ssh deployer_copyright@42.62.77.86"

alias e='emacs -nw'
# alias emd='emacs --daemon'
alias g=git         
alias gst='git status'
alias gbr='git branch'


alias ftpd="sudo /usr/local/Cellar/proftpd/1.3.4d/sbin/proftpd"
# alias tcpinfo='netstat -n | awk "/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}"'
alias sftpstage='sftp deployer@src.najaplus.com'
# alias dev12="cd $GOPATH/src/zerogame.info/thserver/thserver&& ./dev.sh 1 2"
alias download="cd ~/Downloads/"
alias cdg="cd $GOPAtH"
alias cdbin="cd $GOPAtH/bin/"
alias cdd="cd -"
alias joseph="cd ~/.emacs.d/site-lisp/joseph/"
# ssh通过代理
#alias erl='rlwrap -a  erl'
# alias arp='sudo arp'
# alias mysqld='sudo /etc/init.d/mysql restart'
# alias rr='sudo revdep-rebuild -- keep-going;sudo perl-cleaner --all;lafilefixer --justfixit;sudo python-updater;prelink -amR'
# alias eupdatep='sudo emerge -uvDNp --keep-going world>>/tmp/emerge.log 2>&1 '
# alias eupdatec='sudo emerge -uvDN --keep-going world>>/tmp/emerge.log 2>&1 &!'
# alias eupdate='sudo emerge -uvDN --keep-going world>>/tmp/emerge.log 2>&1'
# alias esync="sudo emerge --sync>>/tmp/emerge.log 2>&1&& sudo layman -S ;sudo eix-update>>/tmp/emerge.log 2>&1"
# alias logout="echo 'awesome.quit()'|awesome-client"
# alias emacsd="sudo /etc/init.d/emacs.$USER restart"
# alias emacsq="emacs -q -debug-init"
# alias sftp="sudo /etc/init.d/proftpd restart"
if [ $(uname -s ) = "Linux" ] ; then
    alias ls='ls --color=auto  --time-style=+"%m月%d日 %H:%M"'
    alias la='ls -a --color=auto  '
    alias ll='ls -lth --color=auto --time-style=+"%m月%d日 %H:%M"'
    # sort by time 倒序
    alias llr='ls -lrth --color=auto --time-style=+"%m月%d日 %H:%M"'
    # sort by time
    alias lla='ls -alth --color=auto --time-style=+"%m月%d日 %H:%M"'
    # sort by size
    alias lls='ls -lSh --color=auto --time-style=+"%m月%d日 %H:%M"'
    # sort by name
    alias lln='ls -lh --color=auto --time-style=+"%m月%d日 %H:%M"'
    alias ip="ifconfig eth0"
else
    #-v  http:/lujun.info/2012/10/osx-%E7%9A%84-iterm2%E4%B8%AD%E6%98%BE%E7%A4%BA%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F/
    alias ip='ifconfig en0'
    alias ipconfig='ifconfig en0'

    # -G color
    alias ls='ls -Gv '
    alias la='ls -aGvv'
    #  -t 按时间排 时间最近的在前面 ,加-r 则反向
    alias ll='ls -lthGv'
    alias llr='ls -ltrhGv'
    alias lla='ls -althGv'
    # sort by size
    alias lls='ls -lShGv'
    # default sort by name
    alias lln='ls -lhGv'
    # sort by cpu
    alias topc='top -o cpu'
    # sort by mreg(memory region)
    alias topm='top -o mreg'
    alias gdb='sudo gdb'
    alias ip="ifconfig en0"

fi
alias sl='ls'
alias mkdir='mkdir -p'
alias cp='cp -r'
alias rm="rm -rf"
alias lp='ls|less'
alias ps='ps -ef'
alias pp='ps -ef|grep'
alias su="su -l"
alias "df-h"="df -h"
alias -g ....=" ../../.."
alias -g .....=" ../../../.."
alias -g ...=" ../.."
alias ..="cd .."
alias cd..="cd .."
alias d='dirs -v | head -10'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias cd1='cd -'
alias cd2='cd -2'
alias cd3='cd -3'
alias cd4='cd -4'
alias cd5='cd -5'
alias cd6='cd -6'
alias cd7='cd -7'
alias cd8='cd -8'
alias cd9='cd -9'


# alias s=" rc-service"
# alias rs=" rc-service"
# alias rc-status="sudo rc-status"
# alias rc-update="sudo rc-update"
alias xterm='xterm -sl 1500'
alias sqlplus="rlwrap sqlplus"
alias dush="du -sh"

alias v='sudo vim'
# alias vi='em'
alias k="pkill  -f "
alias kk="pkill  -9 -f "
alias kkk="sudo pkill  -9 -f "
#alias drd="sudo drcomd"
# alias net="sudo /etc/init.d/net.eth0 restart"
# alias ifconfig="sudo ifconfig"
# alias route="sudo route"
# alias halt="sync;sudo shutdown -h now"
# alias reboot="sync;sudo reboot"
alias mount="sudo mount"
alias umount="sudo umount"
alias ettercap="sudo ettercap "
# alias env-update="sudo env-update"
# alias etc-update="sudo etc-update"
alias date="date +%Y-%m-%d_%H:%M-%A"

#export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] "
#export PS1="\[\e[01;32m\]\u\[\e[01;34m\] \W \$\[\e[00m\] "

# alias net="sudo rm /var/lib/dhcpcd/dhcpcd-eth0.lease;sudo /etc/init.d/net.eth0 restart"
alias df="df -h"
# alias light="echo -n 40|sudo tee /proc/acpi/video/VGA/LCD/brightness"
# alias du="du -sh"
# }}}
alias -s html=vi   # 在命令行直接输入后缀为 html 的文件名，会在 TextMate 中打开
# alias -s rb=vi     # 在命令行直接输入 ruby 文件，会在 TextMate 中打开
# alias -s py=vi       # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
alias -s js=vi
alias -s c=vi
alias -s java=vi
alias -s txt=vi
alias -s el=ec
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'
