#!/bin/zsh
#
alias tumx='tmux'
alias ta='tmux attach'
alias tt='tmux new -A -s $HOST'
tmux_porcess_cnt=`pgrep tmux |wc -l`

if [ $tmux_porcess_cnt -eq 0  ] ; then
    tmux new -A -s $HOST
else
    echo "tt for tmux new -A -s $HOST"
    echo "ta for tmux attach"
fi

alias ubuntu="ssh ubuntu@42.62.77.86"
alias deployer="ssh deployer@42.62.77.86"
alias copyright="ssh deployer_copyright@42.62.77.86"

alias g=git         
alias gst='git status'
alias gbr='git branch'

alias sftpstage='sftp deployer@42.62.77.86'
alias gen="cd '/Users/jixiuf/repos/godlike/design/数值'&& sh ./gen_sql_server.sh && cd -"
alias genclent="cd '/Users/jixiuf/快盘商业版/publicbox.localized/数值/'&& sh ./gen_sql_client.sh && cd -"
alias build="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/&& ./build_dev.sh&& cd -"
alias b="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/&& ./build_dev.sh&& cd -"
alias dev="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/pvemain&& ./dev.sh"
alias rob="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/pvemain&& ./robot.sh"
alias robo="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/robot&& ./run&& cd -"
alias pro="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/pvemain&& ./pro.sh&& cd -"
alias one_key_dev="cd /Users/jixiuf/repos/proj_golang/src/zerogame.info/thserver/&& ./one_key_dev.sh&& cd -"
alias download="cd ~/Downloads/"
alias cdg="cd ~/repos/proj_golang"
alias godlike="cd ~/repos/godlike"
alias cdgbin="cd ~/repos/proj_golang/bin/"
alias bin="cd ~/repos/proj_golang/bin/"
alias cdgsrc="cd ~/repos/proj_golang/src/zerogame.info/thserver/"
alias src="cd ~/repos/proj_golang/src/zerogame.info/thserver/"
alias cdgpkg="cd ~/repos/proj_golang/pkg/darwin_amd64/"
alias pkg="cd ~/repos/proj_golang/pkg/darwin_amd64/zerogame.info/thserver/"
alias cdd="cd -"
alias joseph="cd ~/.emacs.d/site-lisp/joseph/"
# ssh通过代理
alias yanfa="TERM=rxvt sudo ssh -o ProxyCommand='socat - socks:122.224.249.55:%h:%p,socksport=9991' app100622829@10.142.8.24 -p 36000"
#alias erl='rlwrap -a  erl'
# alias arp='sudo arp'
# alias mysqld='sudo /etc/init.d/mysql restart'
# alias rr='sudo revdep-rebuild -- keep-going;sudo perl-cleaner --all;lafilefixer --justfixit;sudo python-updater;prelink -amR'
# alias eupdatep='sudo emerge -uvDNp --keep-going world>>/tmp/emerge.log 2>&1 '
# alias eupdatec='sudo emerge -uvDN --keep-going world>>/tmp/emerge.log 2>&1 &!'
# alias eupdate='sudo emerge -uvDN --keep-going world>>/tmp/emerge.log 2>&1'
# alias esync="sudo emerge --sync>>/tmp/emerge.log 2>&1&& sudo layman -S ;sudo eix-update>>/tmp/emerge.log 2>&1"
# alias logout="echo 'awesome.quit()'|awesome-client"
# alias emacsd="sudo /etc/init.d/emacs.$USER restart"
# alias emacsq="emacs -q -debug-init"
# alias sftp="sudo /etc/init.d/proftpd restart"
if [ $(uname -s ) = "Linux" ] ; then
    alias ls='ls --color=auto  --time-style=+"%m月%d日 %H:%M"'
    alias la='ls -a --color=auto  '
    alias ll='ls -lth --color=auto --time-style=+"%m月%d日 %H:%M"'
    alias lla='ls -alth --color=auto --time-style=+"%m月%d日 %H:%M"'
    alias ip="ifconfig eth0"
else
    #-v  http:/lujun.info/2012/10/osx-%E7%9A%84-iterm2%E4%B8%AD%E6%98%BE%E7%A4%BA%E4%B8%AD%E6%96%87%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F/
    alias ip='ifconfig en0'
    alias ipconfig='ifconfig en0'
    alias ls='ls -Gv '
    alias la='ls -aGvv'
    alias ll='ls -lthGv'
    alias lla='ls -althGv'
    # sort by cpu
    alias topc='top -o cpu'
    # sort by mreg(memory region)
    alias topm='top -o mreg'
    alias gdb='sudo gdb'
    alias ip="ifconfig en0"

fi
alias sl='ls'
alias mkdir='mkdir -p'
alias cp='cp -r'
alias rm="rm -rf"
alias lp='ls|less'
alias lls='ls'
alias ps='ps -ef'
alias pp='ps -ef|grep '
alias su="su -l"
alias "df-h"="df -h"
alias -g ...=" ../.."
alias ..="cd .."
alias cd..="cd .."
# alias s=" rc-service"
# alias rs=" rc-service"
# alias rc-status="sudo rc-status"
# alias rc-update="sudo rc-update"
alias xterm='xterm -sl 1500'
alias sqlplus="rlwrap sqlplus"
alias dush="du -sh"

alias v='sudo vim'
alias k="pkill  -9 -f "
alias kk="sudo pkill  -9 -f "
#alias drd="sudo drcomd"
# alias net="sudo /etc/init.d/net.eth0 restart"
# alias ifconfig="sudo ifconfig"
# alias route="sudo route"
# alias halt="sync;sudo shutdown -h now"
# alias reboot="sync;sudo reboot"
alias mount="sudo mount"
alias umount="sudo umount"
alias ettercap="sudo ettercap "
# alias env-update="sudo env-update"
# alias etc-update="sudo etc-update"
alias date="date +%Y-%m-%d_%H:%M-%A"

#export PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] "
#export PS1="\[\e[01;32m\]\u\[\e[01;34m\] \W \$\[\e[00m\] "

# alias net="sudo rm /var/lib/dhcpcd/dhcpcd-eth0.lease;sudo /etc/init.d/net.eth0 restart"
alias df="df -h"
# alias light="echo -n 40|sudo tee /proc/acpi/video/VGA/LCD/brightness"
# alias du="du -sh"
# }}}
alias -s html=vi   # 在命令行直接输入后缀为 html 的文件名，会在 TextMate 中打开
alias -s rb=vi     # 在命令行直接输入 ruby 文件，会在 TextMate 中打开
alias -s py=vi       # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
alias -s js=vi
alias -s c=vi
alias -s java=vi
alias -s txt=vi
alias -s el=ec
alias -s gz='tar -xzvf'
alias -s tgz='tar -xzvf'
alias -s zip='unzip'
alias -s bz2='tar -xjvf'
