#!/bin/zsh
export GOROOT=/usr/local/go
appendPath "$GOROOT/bin"
export GOPATH=/Users/jixiuf/repos/proj_golang
appendPath "$GOPATH/bin"
export  ALTERNATE_EDITOR=/Applications/Emacs.app/Contents/MacOS/Emacs
