#!/bin/zsh
if [ -d /usr/local/go ]; then
    export GOROOT=/usr/local/go
fi
appendPath "$GOROOT/bin"
export GOPATH=/Users/jixiuf/repos/proj_golang
appendPath "$GOPATH/bin"

# emacsDaemonCount=`pgrep -f "emacs --daemon"|wc -l`
# if [ $emacsDaemonCount -eq 0 ]; then
#     emacs --daemon >/tmp/emacs-daemon.log 2>&1 & 
# fi

if [ -f /usr/local/Library/Contributions/brew_zsh_completion.zsh ]; then
    ln -s -f /usr/local/Library/Contributions/brew_zsh_completion.zsh ~/.zsh/site-functions/_brew
fi
if [ -d /usr/local/include/ ]; then
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include/
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/include/
    export OBJC_INCLUDE_PATH=$OBJC_INCLUDE_PATH:/usr/local/include/
fi
if [ -d /usr/local/lib/ ]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
fi
if [ -d /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include ]; then
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include 
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include 
    export OBJC_INCLUDE_PATH=$OBJC_INCLUDE_PATH:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include 
fi
if [ -d /usr/local/opt/opencv3 ]; then
    export OpenCV_DIR=/usr/local/opt/opencv3
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:$OpenCV_DIR/include
    export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$OpenCV_DIR/include
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OpenCV_DIR/lib
fi